# Generated by Django 5.1.15 on 2026-04-19 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('waist', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=6, null=True)),
                ('neck', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=6, null=True)),
                ('hip', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=6, null=True)),
                ('fitness_goals', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
